### ISSUE TITLE
Markers that refresh at server reset time

### ISSUE THREAD

**Issue by luaneko** [chiyadev/genshin-schedule#15]
Some crystal chunks respawn at server reset time starting 1.1

**Comment by RaffaeleAmmirati** [comment]
Since not resin monster respawn at server reset 4:00 AM. Can we make all the pin for the monster drop reset at server reset?
![pin reset](https://user-images.githubusercontent.com/59028378/100350875-df4ab500-2fea-11eb-914d-207cd5dd9726.png)

Even if the pin are already present I made a list of the monster drop that reset at server reset:
Slime
Hilichurl Masks
Hilichurl Arrowheads
Samachurl Scrolls
Treasure Hoarder Insignias
Fatui Insignias
Whopperflower Nectar
Hilichurl Horns
Line Law
Bone Shards
Mist Grass
Fatui Knives
Chaos Parts

I also noticed that the pin for the bamboo and the pearl are missing. The bamboo is considered a local speciality and respaw evry 2 days like the other.

Thank you.

**Comment by luaneko** [comment]
This is very useful! Thank you, I'll add these on the next update.

**Comment by luaneko** [comment]
This has been implemented! You can select "server reset" option in the dropdown. I've also added a few more missing items including bamboo and loach pearl.

![image](https://user-images.githubusercontent.com/27663662/100575015-5d7ec280-332f-11eb-8b69-5c05033dcfb3.png)
