### ISSUE TITLE
Task search does not filter items in the task list

### ISSUE THREAD

**Issue by luaneko** [chiyadev/genshin-schedule#42]
Task list should be hiding mismatches but it does not. Current:

![image](https://user-images.githubusercontent.com/27663662/105467113-577edf80-5ce9-11eb-81b2-175eeb36f179.png)

Expected:

![image](https://user-images.githubusercontent.com/27663662/105467221-7d0be900-5ce9-11eb-83f9-453a2f56ac65.png)

Map is unaffected and works as expected.

**Comment by lauslim12** [comment]
I think I found the bug.

I noticed that your `useDueTasks` utility function does not actually search for the query that we typed in the search box. So, I modified your `useDueTasks` code a bit and...

![image](https://user-images.githubusercontent.com/31909304/105478041-3f9d6080-5cd5-11eb-9d98-630715ac509d.png)

![image](https://user-images.githubusercontent.com/31909304/105478060-45934180-5cd5-11eb-916a-045513741e84.png)

![image](https://user-images.githubusercontent.com/31909304/105478086-4c21b900-5cd5-11eb-941e-ef3453691701.png)

Works perfectly! What do you think? I can drop a PR if you wish!

**Comment by luaneko** [comment]
That would be great!

**Comment by lauslim12** [comment]
I guess my solution was incorrect 😅.

Thanks for the feedback though, if I managed to find another solution that suits your feedback, I'll make a PR again.

**Comment by lauslim12** [comment]
Hey, I think I managed to find a solution according to your feedback.

It's actually pretty simple, it goes like the following:

Old one:

```ts
const dueTasks = useDueTasks(tasks);
```

New one:

```ts
const dueTasks = useDueTasks(tasks);
const filteredTasks = useFilteredTasks(dueTasks); // after getting due tasks, filter them according to the user's query.

// The next parts are just replacing 'dueTasks' with 'filteredTasks'
```

I believe the reason of why the search button never worked - is because we never called `useFilteredTasks` in the first place. The reason the map worked fine is because we have called the `useFilteredTasks` function in the `taskDispatches` (`TaskLayer` component).

All of the changes happen in the `TaskListCard`.

What do you think? I tested in it my local machine and it works perfectly. Hope it doesn't incur any of negative side effects or bugs though!

**Comment by luaneko** [comment]
That's what I was looking for :)
