### ISSUE TITLE
Daylight Timezone Support

### ISSUE THREAD

**Issue by lostguru** [chiyadev/genshin-schedule#54]
Most countries in North America and Europe observe Daylight Savings Time, where clocks are set forward one hour for half of the year. Currently the website doesn't account for this when displaying times.

As an example, for timezones such as `America/New_York`, currently the time should be displayed in Eastern Daylight Time (EDT, or UTC-04:00), but it is still displayed in Eastern Standard Time (EST, or UTC-05:00)

Daylight Savings Time is complicated and varies in implementation between countries, so it'd probably be easiest to use something like [moment.js and moment-timezone](https://momentjs.com/timezone/) to take care of that stuff. If this isn't feasible or too time consuming, a simple manual toggle in the Settings menu would be enough. (e.g. checking a checkbox would add an hour to all times displayed)

**Comment by luaneko** [comment]
moment.js is [deprecated](https://momentjs.com/docs/#/-project-status/), so we are currently using Luxon for date calculation. [This code](https://github.com/chiyadev/genshin-schedule/blob/master/web/utils/time.ts#L34) is responsible for determining the server timezone, but it's not considering DST because it returns UTC offsets instead of actual timezones.

**Comment by bzz3** [comment]
Oh wow, I didn't know Moment wasn't getting updated anymore. In that case I'll leave things to your better judgement.

**Comment by lostguru** [comment]
Oh wow, I didn't know Moment wasn't getting updated anymore. In that case I'll leave things to your better judgement.

**Comment by luaneko** [comment]
Fixed!
